### ISSUE TITLE
Strict warnings : Only variables should be passed by reference in mdl_library_info_alter()

### ISSUE THREAD

**Issue by tanmayk** [andreapaiola/d8mdl#1]
After installing the theme, I am getting warnings as Only variables should be passed by reference in mdl_library_info_alter() in line 7 and 8 of mdl.theme.

The code in mdl_library_info_alter() can be changed as below:

```
$mdlCSSKeys = array_keys($libraries['mdl']['css']['theme']);
$oldCSSKey = array_shift($mdlCSSKeys);
$mdlJSKeys = array_keys($libraries['mdl']['js']);
$oldJSKey = array_shift($mdlJSKeys);
```

**Comment by andreapaiola** [comment]
Thank you, I'll take a look ASAP.

 I think that is related to a specific PHP version... so please report the PHP version.

**Comment by tanmayk** [comment]
I am getting this on PHP 5.6

**Comment by andreapaiola** [comment]
The warning happens because array_pop expects the parameter to be a reference to a stored variable.
So, yes, adding a dummy variable should fix it.
