### ISSUE TITLE
Please review pull requests #3, #4, #5, #6, #7, #8, #9, #10

### ISSUE THREAD

**Issue by beatchristen** [andreapaiola/d8mdl#11]
Hi Andrea
thanks for the nice work on getting MDL up for D8.
please have a look at the pull requests I've dropped. Feel free to fork, extend, ignore, etc. Whatever you feel belongs.
Some of the extra twig files could have been turned into preprocess functions, sometimes the removal of the extensive <div>-battle drupal is having might lose some attributes (e.g. textarea lost some attributes)

**Comment by andreapaiola** [comment]
Sure, thank you for the effort. 
I'm very busy, but ASAP I'll take a look.

**Comment by beatchristen** [comment]
Well, thank you for putting in the base! I will be adding a bunch of other MDL-ish things in the coming weeks, so no need to hurry.

Regarding #10: The selectfield is probably not in the right place in the mdl-theme, so I started a mdlui-companion module for the more complicated components. So I will put that one on hold for the moment.

No hurries.

**Comment by andreapaiola** [comment]
OK, now I have merged a lot! Starting to test in localhost with Drupal 8.3.1 and if it will be bugs... will see!
