### ISSUE TITLE
Add HTML input type "email" support

### ISSUE THREAD

**Issue by andreapaiola** [andreapaiola/d8mdl#14]
HTML input type "email" support is a standard in Drupal
![schermata del 2017-04-22 11 42 03](https://cloud.githubusercontent.com/assets/16450997/25303343/e8268560-2750-11e7-859c-c0ea0963cf3f.png)

Suggestions for the implementation?

**Comment by beatchristen** [comment]
@andreapaiola 

try to add it to the already known types at
https://github.com/andreapaiola/d8mdl/blob/master/mdl.theme#L204

If MDL has some special css classes for emails as well, then this is the place to massage in the classname.

**Comment by andreapaiola** [comment]
What a beauty :+1: 

![schermata del 2017-06-10 10 38 56](https://user-images.githubusercontent.com/16450997/27001407-a287cb14-4dc9-11e7-8ab3-d42bcb0181ff.png)
