### ISSUE TITLE
Change color not working 

### ISSUE THREAD

**Issue by 4cruzeta** [andreapaiola/d8mdl#16]
Hi, I tried to change the Primary and Accent colors at theme settings panel but it is not working.
When I change footer I see the difference, but the colors can not be changed.
Any clues?
Thaks.

**Comment by andreapaiola** [comment]
Hi, it seems fine to me.
Do you have the cache cleared?
You can use the Devel module or drush to clear the cache.
https://www.drupal.org/node/2598914
